/**
 * Design tokens, the single source of truth for the visual language shared by
 * the Next.js/MUI app (`apps/web`) and the Docusaurus wiki (`apps/docs`).
 *
 * Consumption:
 *  - `apps/web`  maps these values into the MUI theme (see apps/web/src/theme.ts)
 *                and imports the generated `tokens.css` for non-MUI styling.
 *  - `apps/docs` imports the generated `tokens.css` and maps Infima variables to it.
 *
 * The CSS file `tokens.css` is GENERATED from this module via `bun run build`
 * (scripts/build-css.ts). Never hand-edit tokens.css.
 *
 * Palette: white surfaces, a blue primary and a pink accent, tied together by a
 * pink → violet → blue brand gradient.
 */

export const tokens = {
  color: {
    // Brand: blue (primary).
    brand: {
      50: '#eff6ff',
      100: '#dbeafe',
      200: '#bfdbfe',
      300: '#93c5fd',
      400: '#60a5fa',
      500: '#3b82f6',
      600: '#2563eb',
      700: '#1d4ed8',
      800: '#1e40af',
      900: '#1e3a8a',
    },
    // Accent: pink.
    accent: {
      50: '#fdf2f8',
      100: '#fce7f3',
      200: '#fbcfe8',
      300: '#f9a8d4',
      400: '#f472b6',
      500: '#ec4899',
      600: '#db2777',
      700: '#be185d',
      800: '#9d174d',
      900: '#831843',
    },
    neutral: {
      0: '#ffffff',
      50: '#f8fafc',
      100: '#f1f5f9',
      200: '#e2e8f0',
      300: '#cbd5e1',
      400: '#94a3b8',
      500: '#64748b',
      600: '#475569',
      700: '#334155',
      800: '#1e293b',
      900: '#0f172a',
    },
    success: '#16a34a',
    warning: '#d97706',
    error: '#dc2626',
    info: '#0284c7',
  },
  // Signature gradients (pink → violet → blue).
  gradient: {
    brand: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 50%, #3b82f6 100%)',
    'brand-soft': 'linear-gradient(135deg, #fce7f3 0%, #ede9fe 50%, #dbeafe 100%)',
  },
  font: {
    sans: "var(--font-sans, 'Inter', system-ui, -apple-system, Segoe UI, Roboto, sans-serif)",
    mono: "var(--font-mono, 'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, monospace)",
  },
  radius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '20px',
    full: '9999px',
  },
  space: {
    1: '4px',
    2: '8px',
    3: '12px',
    4: '16px',
    5: '24px',
    6: '32px',
    8: '48px',
    10: '64px',
  },
} as const;

export type Tokens = typeof tokens;

/** Semantic, theme-facing aliases. These are what apps should prefer to reference. */
export const semantic = {
  light: {
    'color-primary': tokens.color.brand[600],
    'color-primary-strong': tokens.color.brand[700],
    'color-primary-contrast': tokens.color.neutral[0],
    'color-accent': tokens.color.accent[500],
    'color-accent-strong': tokens.color.accent[600],
    'color-bg': tokens.color.neutral[0],
    'color-surface': tokens.color.neutral[50],
    'color-border': tokens.color.neutral[200],
    'color-text': tokens.color.neutral[900],
    'color-text-muted': tokens.color.neutral[500],
    'color-success': tokens.color.success,
    'color-warning': tokens.color.warning,
    'color-error': tokens.color.error,
    'color-info': tokens.color.info,
    'gradient-brand': tokens.gradient.brand,
  },
  dark: {
    'color-primary': tokens.color.brand[400],
    'color-primary-strong': tokens.color.brand[300],
    'color-primary-contrast': tokens.color.neutral[900],
    'color-accent': tokens.color.accent[400],
    'color-accent-strong': tokens.color.accent[300],
    'color-bg': tokens.color.neutral[900],
    'color-surface': tokens.color.neutral[800],
    'color-border': tokens.color.neutral[700],
    'color-text': tokens.color.neutral[50],
    'color-text-muted': tokens.color.neutral[400],
    'color-success': tokens.color.success,
    'color-warning': tokens.color.warning,
    'color-error': tokens.color.error,
    'color-info': tokens.color.info,
    'gradient-brand': tokens.gradient.brand,
  },
} as const;

const prefix = 'jl';

function flatten(obj: Record<string, unknown>, path: string[] = []): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(obj)) {
    const next = [...path, key];
    if (value && typeof value === 'object') {
      Object.assign(out, flatten(value as Record<string, unknown>, next));
    } else {
      out[next.join('-')] = String(value);
    }
  }
  return out;
}

function block(selector: string, vars: Record<string, string>): string {
  const lines = Object.entries(vars).map(([k, v]) => `  --${prefix}-${k}: ${v};`);
  return `${selector} {\n${lines.join('\n')}\n}`;
}

/** Build the full CSS variables stylesheet from the tokens above. */
export function buildTokensCss(): string {
  const primitives = flatten(tokens);
  return [
    '/* GENERATED by @julia/tokens, do not edit. Run `bun run build` in packages/tokens. */',
    block(':root', { ...primitives, ...semantic.light }),
    block("[data-theme='dark']", semantic.dark),
    '',
  ].join('\n\n');
}
