import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Auto-generated from the docs/ folder structure. Article order is controlled by
// `sidebar_position` front matter and `_category_.json` files.
const sidebars: SidebarsConfig = {
  wikiSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
